// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const TRANSFORMCALC_METADATA: Metadata = {
    id: "2f74a41ba813f5fe4e69185ab7204bfa0a360cab.boutiques",
    name: "transformcalc",
    package: "mrtrix",
    container_image_tag: "mrtrix3/mrtrix3:3.0.4",
};


interface TransformcalcConfigParameters {
    "@type": "mrtrix.transformcalc.config";
    "key": string;
    "value": string;
}


interface TransformcalcParameters {
    "@type": "mrtrix.transformcalc";
    "info": boolean;
    "quiet": boolean;
    "debug": boolean;
    "force": boolean;
    "nthreads"?: number | null | undefined;
    "config"?: Array<TransformcalcConfigParameters> | null | undefined;
    "help": boolean;
    "version": boolean;
    "inputs": Array<string>;
    "operation": string;
    "output": string;
}


/**
 * Get build cargs function by command type.
 *
 * @param t Command type
 *
 * @returns Build cargs function.
 */
function dynCargs(
    t: string,
): Function | undefined {
    const cargsFuncs = {
        "mrtrix.transformcalc": transformcalc_cargs,
        "mrtrix.transformcalc.config": transformcalc_config_cargs,
    };
    return cargsFuncs[t];
}


/**
 * Get build outputs function by command type.
 *
 * @param t Command type
 *
 * @returns Build outputs function.
 */
function dynOutputs(
    t: string,
): Function | undefined {
    const outputsFuncs = {
        "mrtrix.transformcalc": transformcalc_outputs,
    };
    return outputsFuncs[t];
}


/**
 * Build parameters.
 *
 * @param key temporarily set the value of an MRtrix config file entry.
 * @param value temporarily set the value of an MRtrix config file entry.
 *
 * @returns Parameter dictionary
 */
function transformcalc_config_params(
    key: string,
    value: string,
): TransformcalcConfigParameters {
    const params = {
        "@type": "mrtrix.transformcalc.config" as const,
        "key": key,
        "value": value,
    };
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function transformcalc_config_cargs(
    params: TransformcalcConfigParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("-config");
    cargs.push((params["key"] ?? null));
    cargs.push((params["value"] ?? null));
    return cargs;
}


/**
 * Output object returned when calling `transformcalc(...)`.
 *
 * @interface
 */
interface TransformcalcOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * the output transformation matrix.
     */
    output: OutputPathType;
}


/**
 * Build parameters.
 *
 * @param inputs the input(s) for the specified operation
 * @param operation the operation to perform, one of: invert, half, rigid, header, average, interpolate, decompose, align_vertices_rigid, align_vertices_rigid_scale (see description section for details).
 * @param output the output transformation matrix.
 * @param info display information messages.
 * @param quiet do not display information messages or progress status; alternatively, this can be achieved by setting the MRTRIX_QUIET environment variable to a non-empty string.
 * @param debug display debugging messages.
 * @param force force overwrite of output files (caution: using the same file as input and output might cause unexpected behaviour).
 * @param nthreads use this number of threads in multi-threaded applications (set to 0 to disable multi-threading).
 * @param config temporarily set the value of an MRtrix config file entry.
 * @param help display this information page and exit.
 * @param version display version information and exit.
 *
 * @returns Parameter dictionary
 */
function transformcalc_params(
    inputs: Array<string>,
    operation: string,
    output: string,
    info: boolean = false,
    quiet: boolean = false,
    debug: boolean = false,
    force: boolean = false,
    nthreads: number | null = null,
    config: Array<TransformcalcConfigParameters> | null = null,
    help: boolean = false,
    version: boolean = false,
): TransformcalcParameters {
    const params = {
        "@type": "mrtrix.transformcalc" as const,
        "info": info,
        "quiet": quiet,
        "debug": debug,
        "force": force,
        "help": help,
        "version": version,
        "inputs": inputs,
        "operation": operation,
        "output": output,
    };
    if (nthreads !== null) {
        params["nthreads"] = nthreads;
    }
    if (config !== null) {
        params["config"] = config;
    }
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function transformcalc_cargs(
    params: TransformcalcParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("transformcalc");
    if ((params["info"] ?? null)) {
        cargs.push("-info");
    }
    if ((params["quiet"] ?? null)) {
        cargs.push("-quiet");
    }
    if ((params["debug"] ?? null)) {
        cargs.push("-debug");
    }
    if ((params["force"] ?? null)) {
        cargs.push("-force");
    }
    if ((params["nthreads"] ?? null) !== null) {
        cargs.push(
            "-nthreads",
            String((params["nthreads"] ?? null))
        );
    }
    if ((params["config"] ?? null) !== null) {
        cargs.push(...(params["config"] ?? null).map(s => dynCargs(s["@type"])(s, execution)).flat());
    }
    if ((params["help"] ?? null)) {
        cargs.push("-help");
    }
    if ((params["version"] ?? null)) {
        cargs.push("-version");
    }
    cargs.push(...(params["inputs"] ?? null));
    cargs.push((params["operation"] ?? null));
    cargs.push((params["output"] ?? null));
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function transformcalc_outputs(
    params: TransformcalcParameters,
    execution: Execution,
): TransformcalcOutputs {
    const ret: TransformcalcOutputs = {
        root: execution.outputFile("."),
        output: execution.outputFile([(params["output"] ?? null)].join('')),
    };
    return ret;
}


/**
 * transformcalc
 *
 * Perform calculations on linear transformation matrices.
 *
 *
 *
 * References:
 *
 * .
 *
 * Author: MRTrix3 Developers
 *
 * URL: https://www.mrtrix.org/
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `TransformcalcOutputs`).
 */
function transformcalc_execute(
    params: TransformcalcParameters,
    runner: Runner | null = null,
): TransformcalcOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(TRANSFORMCALC_METADATA);
    params = execution.params(params)
    const cargs = transformcalc_cargs(params, execution)
    const ret = transformcalc_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * transformcalc
 *
 * Perform calculations on linear transformation matrices.
 *
 *
 *
 * References:
 *
 * .
 *
 * Author: MRTrix3 Developers
 *
 * URL: https://www.mrtrix.org/
 *
 * @param inputs the input(s) for the specified operation
 * @param operation the operation to perform, one of: invert, half, rigid, header, average, interpolate, decompose, align_vertices_rigid, align_vertices_rigid_scale (see description section for details).
 * @param output the output transformation matrix.
 * @param info display information messages.
 * @param quiet do not display information messages or progress status; alternatively, this can be achieved by setting the MRTRIX_QUIET environment variable to a non-empty string.
 * @param debug display debugging messages.
 * @param force force overwrite of output files (caution: using the same file as input and output might cause unexpected behaviour).
 * @param nthreads use this number of threads in multi-threaded applications (set to 0 to disable multi-threading).
 * @param config temporarily set the value of an MRtrix config file entry.
 * @param help display this information page and exit.
 * @param version display version information and exit.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `TransformcalcOutputs`).
 */
function transformcalc(
    inputs: Array<string>,
    operation: string,
    output: string,
    info: boolean = false,
    quiet: boolean = false,
    debug: boolean = false,
    force: boolean = false,
    nthreads: number | null = null,
    config: Array<TransformcalcConfigParameters> | null = null,
    help: boolean = false,
    version: boolean = false,
    runner: Runner | null = null,
): TransformcalcOutputs {
    const params = transformcalc_params(inputs, operation, output, info, quiet, debug, force, nthreads, config, help, version)
    return transformcalc_execute(params, runner);
}


export {
      TRANSFORMCALC_METADATA,
      TransformcalcConfigParameters,
      TransformcalcOutputs,
      TransformcalcParameters,
      transformcalc,
      transformcalc_config_params,
      transformcalc_execute,
      transformcalc_params,
};
