// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const FIX_SUBJECT_CORRECTED_RH_METADATA: Metadata = {
    id: "f1bbdaf75a1a8e747d2ce52e84a6d82308c56081.boutiques",
    name: "fix_subject_corrected-rh",
    package: "freesurfer",
    container_image_tag: "freesurfer/freesurfer:7.4.1",
};


interface FixSubjectCorrectedRhParameters {
    "@type"?: "freesurfer/fix_subject_corrected-rh";
    "subject_dir": string;
}
type FixSubjectCorrectedRhParametersTagged = Required<Pick<FixSubjectCorrectedRhParameters, '@type'>> & FixSubjectCorrectedRhParameters;


/**
 * Output object returned when calling `FixSubjectCorrectedRhParameters(...)`.
 *
 * @interface
 */
interface FixSubjectCorrectedRhOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * Log file generated during the execution
     */
    log_file: OutputPathType;
}


/**
 * Build parameters.
 *
 * @param subject_dir Path to the FreeSurfer subject directory
 *
 * @returns Parameter dictionary
 */
function fix_subject_corrected_rh_params(
    subject_dir: string,
): FixSubjectCorrectedRhParametersTagged {
    const params = {
        "@type": "freesurfer/fix_subject_corrected-rh" as const,
        "subject_dir": subject_dir,
    };
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function fix_subject_corrected_rh_cargs(
    params: FixSubjectCorrectedRhParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("fix_subject_corrected-rh");
    cargs.push(
        "-rh",
        (params["subject_dir"] ?? null)
    );
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function fix_subject_corrected_rh_outputs(
    params: FixSubjectCorrectedRhParameters,
    execution: Execution,
): FixSubjectCorrectedRhOutputs {
    const ret: FixSubjectCorrectedRhOutputs = {
        root: execution.outputFile("."),
        log_file: execution.outputFile([(params["subject_dir"] ?? null), "/scripts_output.log"].join('')),
    };
    return ret;
}


/**
 * fix_subject_corrected-rh
 *
 * A tool related to FreeSurfer subject correction.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `FixSubjectCorrectedRhOutputs`).
 */
function fix_subject_corrected_rh_execute(
    params: FixSubjectCorrectedRhParameters,
    runner: Runner | null = null,
): FixSubjectCorrectedRhOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(FIX_SUBJECT_CORRECTED_RH_METADATA);
    params = execution.params(params)
    const cargs = fix_subject_corrected_rh_cargs(params, execution)
    const ret = fix_subject_corrected_rh_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * fix_subject_corrected-rh
 *
 * A tool related to FreeSurfer subject correction.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param subject_dir Path to the FreeSurfer subject directory
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `FixSubjectCorrectedRhOutputs`).
 */
function fix_subject_corrected_rh(
    subject_dir: string,
    runner: Runner | null = null,
): FixSubjectCorrectedRhOutputs {
    const params = fix_subject_corrected_rh_params(subject_dir)
    return fix_subject_corrected_rh_execute(params, runner);
}


export {
      FIX_SUBJECT_CORRECTED_RH_METADATA,
      FixSubjectCorrectedRhOutputs,
      fix_subject_corrected_rh,
      fix_subject_corrected_rh_execute,
      fix_subject_corrected_rh_params,
};
