// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const MAKEVOL_METADATA: Metadata = {
    id: "8802efdad5a767387b2e4e04a7189b59ea97e217.boutiques",
    name: "makevol",
    package: "freesurfer",
    container_image_tag: "freesurfer/freesurfer:7.4.1",
};


interface MakevolParameters {
    "@type"?: "freesurfer/makevol";
    "filename"?: string | null | undefined;
    "width"?: number | null | undefined;
    "height"?: number | null | undefined;
    "depth"?: number | null | undefined;
    "sizex"?: number | null | undefined;
    "sizey"?: number | null | undefined;
    "sizez"?: number | null | undefined;
    "set_method"?: string | null | undefined;
}
type MakevolParametersTagged = Required<Pick<MakevolParameters, '@type'>> & MakevolParameters;


/**
 * Output object returned when calling `MakevolParameters(...)`.
 *
 * @interface
 */
interface MakevolOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * The created volume file.
     */
    output_file: OutputPathType | null;
}


/**
 * Build parameters.
 *
 * @param filename Write volume to the given file name, implying type.
 * @param width Use integer WIDTH as the x dimension.
 * @param height Use integer HEIGHT as the y dimension.
 * @param depth Use integer DEPTH as the z dimension.
 * @param sizex Use float SIZEX as the x resolution.
 * @param sizey Use float SIZEY as the y resolution.
 * @param sizez Use float SIZEZ as the z resolution.
 * @param set_method Use METHOD to fill the values. Methods: xyz, random, constant.
 *
 * @returns Parameter dictionary
 */
function makevol_params(
    filename: string | null = null,
    width: number | null = null,
    height: number | null = null,
    depth: number | null = null,
    sizex: number | null = null,
    sizey: number | null = null,
    sizez: number | null = null,
    set_method: string | null = null,
): MakevolParametersTagged {
    const params = {
        "@type": "freesurfer/makevol" as const,
    };
    if (filename !== null) {
        params["filename"] = filename;
    }
    if (width !== null) {
        params["width"] = width;
    }
    if (height !== null) {
        params["height"] = height;
    }
    if (depth !== null) {
        params["depth"] = depth;
    }
    if (sizex !== null) {
        params["sizex"] = sizex;
    }
    if (sizey !== null) {
        params["sizey"] = sizey;
    }
    if (sizez !== null) {
        params["sizez"] = sizez;
    }
    if (set_method !== null) {
        params["set_method"] = set_method;
    }
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function makevol_cargs(
    params: MakevolParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("makevol");
    if ((params["filename"] ?? null) !== null) {
        cargs.push(
            "-f",
            (params["filename"] ?? null)
        );
    }
    if ((params["width"] ?? null) !== null) {
        cargs.push(
            "-x",
            String((params["width"] ?? null))
        );
    }
    if ((params["height"] ?? null) !== null) {
        cargs.push(
            "-y",
            String((params["height"] ?? null))
        );
    }
    if ((params["depth"] ?? null) !== null) {
        cargs.push(
            "-z",
            String((params["depth"] ?? null))
        );
    }
    if ((params["sizex"] ?? null) !== null) {
        cargs.push(
            "--sizex",
            String((params["sizex"] ?? null))
        );
    }
    if ((params["sizey"] ?? null) !== null) {
        cargs.push(
            "--sizey",
            String((params["sizey"] ?? null))
        );
    }
    if ((params["sizez"] ?? null) !== null) {
        cargs.push(
            "--sizez",
            String((params["sizez"] ?? null))
        );
    }
    if ((params["set_method"] ?? null) !== null) {
        cargs.push(
            "--set-method",
            (params["set_method"] ?? null)
        );
    }
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function makevol_outputs(
    params: MakevolParameters,
    execution: Execution,
): MakevolOutputs {
    const ret: MakevolOutputs = {
        root: execution.outputFile("."),
        output_file: ((params["filename"] ?? null) !== null) ? execution.outputFile([(params["filename"] ?? null)].join('')) : null,
    };
    return ret;
}


/**
 * makevol
 *
 * A tool to create a volume with given parameters.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `MakevolOutputs`).
 */
function makevol_execute(
    params: MakevolParameters,
    runner: Runner | null = null,
): MakevolOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(MAKEVOL_METADATA);
    params = execution.params(params)
    const cargs = makevol_cargs(params, execution)
    const ret = makevol_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * makevol
 *
 * A tool to create a volume with given parameters.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param filename Write volume to the given file name, implying type.
 * @param width Use integer WIDTH as the x dimension.
 * @param height Use integer HEIGHT as the y dimension.
 * @param depth Use integer DEPTH as the z dimension.
 * @param sizex Use float SIZEX as the x resolution.
 * @param sizey Use float SIZEY as the y resolution.
 * @param sizez Use float SIZEZ as the z resolution.
 * @param set_method Use METHOD to fill the values. Methods: xyz, random, constant.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `MakevolOutputs`).
 */
function makevol(
    filename: string | null = null,
    width: number | null = null,
    height: number | null = null,
    depth: number | null = null,
    sizex: number | null = null,
    sizey: number | null = null,
    sizez: number | null = null,
    set_method: string | null = null,
    runner: Runner | null = null,
): MakevolOutputs {
    const params = makevol_params(filename, width, height, depth, sizex, sizey, sizez, set_method)
    return makevol_execute(params, runner);
}


export {
      MAKEVOL_METADATA,
      MakevolOutputs,
      makevol,
      makevol_execute,
      makevol_params,
};
