// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const MRI_STRIP_SUBJECT_INFO_METADATA: Metadata = {
    id: "7f018807cf37f338df19c441f6450439090921fb.boutiques",
    name: "mri_strip_subject_info",
    package: "freesurfer",
    container_image_tag: "freesurfer/freesurfer:7.4.1",
};


interface MriStripSubjectInfoParameters {
    "__STYXTYPE__": "mri_strip_subject_info";
    "input_files": Array<InputPathType>;
    "output_directory": string;
}


function dynCargs(
    t: string,
): Function | undefined {
    /**
     * Get build cargs function by command type.
    
     * @param t Command type
    
     * @returns Build cargs function.
     */
    const cargsFuncs = {
        "mri_strip_subject_info": mri_strip_subject_info_cargs,
    };
    return cargsFuncs[t];
}


function dynOutputs(
    t: string,
): Function | undefined {
    /**
     * Get build outputs function by command type.
    
     * @param t Command type
    
     * @returns Build outputs function.
     */
    const outputsFuncs = {
    };
    return outputsFuncs[t];
}


/**
 * Output object returned when calling `mri_strip_subject_info(...)`.
 *
 * @interface
 */
interface MriStripSubjectInfoOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
}


function mri_strip_subject_info_params(
    input_files: Array<InputPathType>,
    output_directory: string,
): MriStripSubjectInfoParameters {
    /**
     * Build parameters.
    
     * @param input_files Input file(s) containing MRI data
     * @param output_directory Directory where stripped files will be saved
    
     * @returns Parameter dictionary
     */
    const params = {
        "__STYXTYPE__": "mri_strip_subject_info" as const,
        "input_files": input_files,
        "output_directory": output_directory,
    };
    return params;
}


function mri_strip_subject_info_cargs(
    params: MriStripSubjectInfoParameters,
    execution: Execution,
): string[] {
    /**
     * Build command-line arguments from parameters.
    
     * @param params The parameters.
     * @param execution The execution object for resolving input paths.
    
     * @returns Command-line arguments.
     */
    const cargs: string[] = [];
    cargs.push("mri_strip_subject_info");
    cargs.push(...(params["input_files"] ?? null).map(f => execution.inputFile(f)));
    cargs.push((params["output_directory"] ?? null));
    return cargs;
}


function mri_strip_subject_info_outputs(
    params: MriStripSubjectInfoParameters,
    execution: Execution,
): MriStripSubjectInfoOutputs {
    /**
     * Build outputs object containing output file paths and possibly stdout/stderr.
    
     * @param params The parameters.
     * @param execution The execution object for resolving input paths.
    
     * @returns Outputs object.
     */
    const ret: MriStripSubjectInfoOutputs = {
        root: execution.outputFile("."),
    };
    return ret;
}


function mri_strip_subject_info_execute(
    params: MriStripSubjectInfoParameters,
    execution: Execution,
): MriStripSubjectInfoOutputs {
    /**
     * A tool to strip subject information from MRI data files.
     * 
     * Author: FreeSurfer Developers
     * 
     * URL: https://github.com/freesurfer/freesurfer
    
     * @param params The parameters.
     * @param execution The execution object.
    
     * @returns NamedTuple of outputs (described in `MriStripSubjectInfoOutputs`).
     */
    params = execution.params(params)
    const cargs = mri_strip_subject_info_cargs(params, execution)
    const ret = mri_strip_subject_info_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


function mri_strip_subject_info(
    input_files: Array<InputPathType>,
    output_directory: string,
    runner: Runner | null = null,
): MriStripSubjectInfoOutputs {
    /**
     * A tool to strip subject information from MRI data files.
     * 
     * Author: FreeSurfer Developers
     * 
     * URL: https://github.com/freesurfer/freesurfer
    
     * @param input_files Input file(s) containing MRI data
     * @param output_directory Directory where stripped files will be saved
     * @param runner Command runner
    
     * @returns NamedTuple of outputs (described in `MriStripSubjectInfoOutputs`).
     */
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(MRI_STRIP_SUBJECT_INFO_METADATA);
    const params = mri_strip_subject_info_params(input_files, output_directory)
    return mri_strip_subject_info_execute(params, execution);
}


export {
      MRI_STRIP_SUBJECT_INFO_METADATA,
      MriStripSubjectInfoOutputs,
      MriStripSubjectInfoParameters,
      mri_strip_subject_info,
      mri_strip_subject_info_params,
};
