// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const MRI_CAL_RENORMALIZE_GCA_METADATA: Metadata = {
    id: "3427802787eacffbf4678b2765d22730cfcc5c16.boutiques",
    name: "mri_cal_renormalize_gca",
    package: "freesurfer",
    container_image_tag: "freesurfer/freesurfer:7.4.1",
};


interface MriCalRenormalizeGcaParameters {
    "@type"?: "freesurfer/mri_cal_renormalize_gca";
    "timepoint_file": InputPathType;
    "in_vol": InputPathType;
    "input_atlas": InputPathType;
    "transform_file": InputPathType;
    "output_atlas": string;
}
type MriCalRenormalizeGcaParametersTagged = Required<Pick<MriCalRenormalizeGcaParameters, '@type'>> & MriCalRenormalizeGcaParameters;


/**
 * Output object returned when calling `MriCalRenormalizeGcaParameters(...)`.
 *
 * @interface
 */
interface MriCalRenormalizeGcaOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * Renormalized output atlas
     */
    output_atlas_file: OutputPathType;
}


/**
 * Build parameters.
 *
 * @param timepoint_file Longitudinal time point file
 * @param in_vol Input volume
 * @param input_atlas Input atlas
 * @param transform_file Transform file
 * @param output_atlas Output atlas
 *
 * @returns Parameter dictionary
 */
function mri_cal_renormalize_gca_params(
    timepoint_file: InputPathType,
    in_vol: InputPathType,
    input_atlas: InputPathType,
    transform_file: InputPathType,
    output_atlas: string,
): MriCalRenormalizeGcaParametersTagged {
    const params = {
        "@type": "freesurfer/mri_cal_renormalize_gca" as const,
        "timepoint_file": timepoint_file,
        "in_vol": in_vol,
        "input_atlas": input_atlas,
        "transform_file": transform_file,
        "output_atlas": output_atlas,
    };
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function mri_cal_renormalize_gca_cargs(
    params: MriCalRenormalizeGcaParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("mri_cal_renormalize_gca");
    cargs.push(execution.inputFile((params["timepoint_file"] ?? null)));
    cargs.push(execution.inputFile((params["in_vol"] ?? null)));
    cargs.push(execution.inputFile((params["input_atlas"] ?? null)));
    cargs.push(execution.inputFile((params["transform_file"] ?? null)));
    cargs.push((params["output_atlas"] ?? null));
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function mri_cal_renormalize_gca_outputs(
    params: MriCalRenormalizeGcaParameters,
    execution: Execution,
): MriCalRenormalizeGcaOutputs {
    const ret: MriCalRenormalizeGcaOutputs = {
        root: execution.outputFile("."),
        output_atlas_file: execution.outputFile([(params["output_atlas"] ?? null)].join('')),
    };
    return ret;
}


/**
 * mri_cal_renormalize_gca
 *
 * Tool for atlas renormalization in FreeSurfer.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `MriCalRenormalizeGcaOutputs`).
 */
function mri_cal_renormalize_gca_execute(
    params: MriCalRenormalizeGcaParameters,
    runner: Runner | null = null,
): MriCalRenormalizeGcaOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(MRI_CAL_RENORMALIZE_GCA_METADATA);
    params = execution.params(params)
    const cargs = mri_cal_renormalize_gca_cargs(params, execution)
    const ret = mri_cal_renormalize_gca_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * mri_cal_renormalize_gca
 *
 * Tool for atlas renormalization in FreeSurfer.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param timepoint_file Longitudinal time point file
 * @param in_vol Input volume
 * @param input_atlas Input atlas
 * @param transform_file Transform file
 * @param output_atlas Output atlas
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `MriCalRenormalizeGcaOutputs`).
 */
function mri_cal_renormalize_gca(
    timepoint_file: InputPathType,
    in_vol: InputPathType,
    input_atlas: InputPathType,
    transform_file: InputPathType,
    output_atlas: string,
    runner: Runner | null = null,
): MriCalRenormalizeGcaOutputs {
    const params = mri_cal_renormalize_gca_params(timepoint_file, in_vol, input_atlas, transform_file, output_atlas)
    return mri_cal_renormalize_gca_execute(params, runner);
}


export {
      MRI_CAL_RENORMALIZE_GCA_METADATA,
      MriCalRenormalizeGcaOutputs,
      mri_cal_renormalize_gca,
      mri_cal_renormalize_gca_execute,
      mri_cal_renormalize_gca_params,
};
