// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const MRIS_REMOVE_NEGATIVE_VERTICES_METADATA: Metadata = {
    id: "5a68aabeda2f4e6811f224288d7f4d9c8c795765.boutiques",
    name: "mris_remove_negative_vertices",
    package: "freesurfer",
    container_image_tag: "freesurfer/freesurfer:7.4.1",
};


interface MrisRemoveNegativeVerticesParameters {
    "@type": "freesurfer.mris_remove_negative_vertices";
    "surface_file": InputPathType;
    "patch_file": InputPathType;
    "output_patch": string;
}


/**
 * Get build cargs function by command type.
 *
 * @param t Command type
 *
 * @returns Build cargs function.
 */
function dynCargs(
    t: string,
): Function | undefined {
    const cargsFuncs = {
        "freesurfer.mris_remove_negative_vertices": mris_remove_negative_vertices_cargs,
    };
    return cargsFuncs[t];
}


/**
 * Get build outputs function by command type.
 *
 * @param t Command type
 *
 * @returns Build outputs function.
 */
function dynOutputs(
    t: string,
): Function | undefined {
    const outputsFuncs = {
        "freesurfer.mris_remove_negative_vertices": mris_remove_negative_vertices_outputs,
    };
    return outputsFuncs[t];
}


/**
 * Output object returned when calling `mris_remove_negative_vertices(...)`.
 *
 * @interface
 */
interface MrisRemoveNegativeVerticesOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * The resulting output patch file
     */
    output_patch_file: OutputPathType;
}


/**
 * Build parameters.
 *
 * @param surface_file Input surface file
 * @param patch_file Patch file name
 * @param output_patch Output patch file
 *
 * @returns Parameter dictionary
 */
function mris_remove_negative_vertices_params(
    surface_file: InputPathType,
    patch_file: InputPathType,
    output_patch: string,
): MrisRemoveNegativeVerticesParameters {
    const params = {
        "@type": "freesurfer.mris_remove_negative_vertices" as const,
        "surface_file": surface_file,
        "patch_file": patch_file,
        "output_patch": output_patch,
    };
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function mris_remove_negative_vertices_cargs(
    params: MrisRemoveNegativeVerticesParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("mris_remove_negative_vertices");
    cargs.push(execution.inputFile((params["surface_file"] ?? null)));
    cargs.push(execution.inputFile((params["patch_file"] ?? null)));
    cargs.push((params["output_patch"] ?? null));
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function mris_remove_negative_vertices_outputs(
    params: MrisRemoveNegativeVerticesParameters,
    execution: Execution,
): MrisRemoveNegativeVerticesOutputs {
    const ret: MrisRemoveNegativeVerticesOutputs = {
        root: execution.outputFile("."),
        output_patch_file: execution.outputFile([(params["output_patch"] ?? null)].join('')),
    };
    return ret;
}


/**
 * mris_remove_negative_vertices
 *
 * This program adds a template into an average surface.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `MrisRemoveNegativeVerticesOutputs`).
 */
function mris_remove_negative_vertices_execute(
    params: MrisRemoveNegativeVerticesParameters,
    runner: Runner | null = null,
): MrisRemoveNegativeVerticesOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(MRIS_REMOVE_NEGATIVE_VERTICES_METADATA);
    params = execution.params(params)
    const cargs = mris_remove_negative_vertices_cargs(params, execution)
    const ret = mris_remove_negative_vertices_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * mris_remove_negative_vertices
 *
 * This program adds a template into an average surface.
 *
 * Author: FreeSurfer Developers
 *
 * URL: https://github.com/freesurfer/freesurfer
 *
 * @param surface_file Input surface file
 * @param patch_file Patch file name
 * @param output_patch Output patch file
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `MrisRemoveNegativeVerticesOutputs`).
 */
function mris_remove_negative_vertices(
    surface_file: InputPathType,
    patch_file: InputPathType,
    output_patch: string,
    runner: Runner | null = null,
): MrisRemoveNegativeVerticesOutputs {
    const params = mris_remove_negative_vertices_params(surface_file, patch_file, output_patch)
    return mris_remove_negative_vertices_execute(params, runner);
}


export {
      MRIS_REMOVE_NEGATIVE_VERTICES_METADATA,
      MrisRemoveNegativeVerticesOutputs,
      MrisRemoveNegativeVerticesParameters,
      mris_remove_negative_vertices,
      mris_remove_negative_vertices_execute,
      mris_remove_negative_vertices_params,
};
