// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const PLOT_STRUCTURE_STATS_TCL_METADATA: Metadata = {
    id: "3de0e97c01ce61e97ae009f4560aa157a2bcc2c6.boutiques",
    name: "plot_structure_stats.tcl",
    package: "freesurfer",
    container_image_tag: "freesurfer/freesurfer:7.4.1",
};


interface PlotStructureStatsTclParameters {
    "__STYXTYPE__": "plot_structure_stats.tcl";
    "input_file": InputPathType;
    "output_file": string;
}


function dynCargs(
    t: string,
): Function | undefined {
    /**
     * Get build cargs function by command type.
    
     * @param t Command type
    
     * @returns Build cargs function.
     */
    const cargsFuncs = {
        "plot_structure_stats.tcl": plot_structure_stats_tcl_cargs,
    };
    return cargsFuncs[t];
}


function dynOutputs(
    t: string,
): Function | undefined {
    /**
     * Get build outputs function by command type.
    
     * @param t Command type
    
     * @returns Build outputs function.
     */
    const outputsFuncs = {
        "plot_structure_stats.tcl": plot_structure_stats_tcl_outputs,
    };
    return outputsFuncs[t];
}


/**
 * Output object returned when calling `plot_structure_stats_tcl(...)`.
 *
 * @interface
 */
interface PlotStructureStatsTclOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * Generated plot
     */
    plot_file: OutputPathType;
}


function plot_structure_stats_tcl_params(
    input_file: InputPathType,
    output_file: string,
): PlotStructureStatsTclParameters {
    /**
     * Build parameters.
    
     * @param input_file Input stats file
     * @param output_file Output plot file
    
     * @returns Parameter dictionary
     */
    const params = {
        "__STYXTYPE__": "plot_structure_stats.tcl" as const,
        "input_file": input_file,
        "output_file": output_file,
    };
    return params;
}


function plot_structure_stats_tcl_cargs(
    params: PlotStructureStatsTclParameters,
    execution: Execution,
): string[] {
    /**
     * Build command-line arguments from parameters.
    
     * @param params The parameters.
     * @param execution The execution object for resolving input paths.
    
     * @returns Command-line arguments.
     */
    const cargs: string[] = [];
    cargs.push("plot_structure_stats.tcl");
    cargs.push(execution.inputFile((params["input_file"] ?? null)));
    cargs.push((params["output_file"] ?? null));
    return cargs;
}


function plot_structure_stats_tcl_outputs(
    params: PlotStructureStatsTclParameters,
    execution: Execution,
): PlotStructureStatsTclOutputs {
    /**
     * Build outputs object containing output file paths and possibly stdout/stderr.
    
     * @param params The parameters.
     * @param execution The execution object for resolving input paths.
    
     * @returns Outputs object.
     */
    const ret: PlotStructureStatsTclOutputs = {
        root: execution.outputFile("."),
        plot_file: execution.outputFile([(params["output_file"] ?? null), ".png"].join('')),
    };
    return ret;
}


function plot_structure_stats_tcl_execute(
    params: PlotStructureStatsTclParameters,
    execution: Execution,
): PlotStructureStatsTclOutputs {
    /**
     * Script to plot structural statistics.
     * 
     * Author: FreeSurfer Developers
     * 
     * URL: https://github.com/freesurfer/freesurfer
    
     * @param params The parameters.
     * @param execution The execution object.
    
     * @returns NamedTuple of outputs (described in `PlotStructureStatsTclOutputs`).
     */
    params = execution.params(params)
    const cargs = plot_structure_stats_tcl_cargs(params, execution)
    const ret = plot_structure_stats_tcl_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


function plot_structure_stats_tcl(
    input_file: InputPathType,
    output_file: string,
    runner: Runner | null = null,
): PlotStructureStatsTclOutputs {
    /**
     * Script to plot structural statistics.
     * 
     * Author: FreeSurfer Developers
     * 
     * URL: https://github.com/freesurfer/freesurfer
    
     * @param input_file Input stats file
     * @param output_file Output plot file
     * @param runner Command runner
    
     * @returns NamedTuple of outputs (described in `PlotStructureStatsTclOutputs`).
     */
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(PLOT_STRUCTURE_STATS_TCL_METADATA);
    const params = plot_structure_stats_tcl_params(input_file, output_file)
    return plot_structure_stats_tcl_execute(params, execution);
}


export {
      PLOT_STRUCTURE_STATS_TCL_METADATA,
      PlotStructureStatsTclOutputs,
      PlotStructureStatsTclParameters,
      plot_structure_stats_tcl,
      plot_structure_stats_tcl_params,
};
