// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const FSLSPLIT_METADATA: Metadata = {
    id: "768b248b1e5d4c026c4c8339b58b3327bf2a83be.boutiques",
    name: "fslsplit",
    package: "fsl",
    container_image_tag: "brainlife/fsl:6.0.4-patched2",
};


interface FslsplitParameters {
    "@type"?: "fsl/fslsplit";
    "infile": InputPathType;
    "output_basename"?: string | null | undefined;
    "separation_x": boolean;
    "separation_y": boolean;
    "separation_z": boolean;
    "separation_time": boolean;
}
type FslsplitParametersTagged = Required<Pick<FslsplitParameters, '@type'>> & FslsplitParameters;


/**
 * Output object returned when calling `FslsplitParameters(...)`.
 *
 * @interface
 */
interface FslsplitOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * Output volumes/slices
     */
    out_files: OutputPathType | null;
}


/**
 * Build parameters.
 *
 * @param infile Input image (e.g. img.nii.gz)
 * @param output_basename Output basename (default: vol)
 * @param separation_x Separate images in the x direction
 * @param separation_y Separate images in the y direction
 * @param separation_z Separate images in the z direction
 * @param separation_time Separate images in time (default behaviour)
 *
 * @returns Parameter dictionary
 */
function fslsplit_params(
    infile: InputPathType,
    output_basename: string | null = null,
    separation_x: boolean = false,
    separation_y: boolean = false,
    separation_z: boolean = false,
    separation_time: boolean = false,
): FslsplitParametersTagged {
    const params = {
        "@type": "fsl/fslsplit" as const,
        "infile": infile,
        "separation_x": separation_x,
        "separation_y": separation_y,
        "separation_z": separation_z,
        "separation_time": separation_time,
    };
    if (output_basename !== null) {
        params["output_basename"] = output_basename;
    }
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function fslsplit_cargs(
    params: FslsplitParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("fslsplit");
    cargs.push(execution.inputFile((params["infile"] ?? null)));
    if ((params["output_basename"] ?? null) !== null) {
        cargs.push((params["output_basename"] ?? null));
    }
    if ((params["separation_x"] ?? false)) {
        cargs.push("-x");
    }
    if ((params["separation_y"] ?? false)) {
        cargs.push("-y");
    }
    if ((params["separation_z"] ?? false)) {
        cargs.push("-z");
    }
    if ((params["separation_time"] ?? false)) {
        cargs.push("-t");
    }
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function fslsplit_outputs(
    params: FslsplitParameters,
    execution: Execution,
): FslsplitOutputs {
    const ret: FslsplitOutputs = {
        root: execution.outputFile("."),
        out_files: ((params["output_basename"] ?? null) !== null) ? execution.outputFile([(params["output_basename"] ?? null)].join('')) : null,
    };
    return ret;
}


/**
 * fslsplit
 *
 * Split a 4D image into separate volumes or a 3D image into separate slices.
 *
 * Author: FMRIB Analysis Group, University of Oxford
 *
 * URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `FslsplitOutputs`).
 */
function fslsplit_execute(
    params: FslsplitParameters,
    runner: Runner | null = null,
): FslsplitOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(FSLSPLIT_METADATA);
    params = execution.params(params)
    const cargs = fslsplit_cargs(params, execution)
    const ret = fslsplit_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * fslsplit
 *
 * Split a 4D image into separate volumes or a 3D image into separate slices.
 *
 * Author: FMRIB Analysis Group, University of Oxford
 *
 * URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
 *
 * @param infile Input image (e.g. img.nii.gz)
 * @param output_basename Output basename (default: vol)
 * @param separation_x Separate images in the x direction
 * @param separation_y Separate images in the y direction
 * @param separation_z Separate images in the z direction
 * @param separation_time Separate images in time (default behaviour)
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `FslsplitOutputs`).
 */
function fslsplit(
    infile: InputPathType,
    output_basename: string | null = null,
    separation_x: boolean = false,
    separation_y: boolean = false,
    separation_z: boolean = false,
    separation_time: boolean = false,
    runner: Runner | null = null,
): FslsplitOutputs {
    const params = fslsplit_params(infile, output_basename, separation_x, separation_y, separation_z, separation_time)
    return fslsplit_execute(params, runner);
}


export {
      FSLSPLIT_METADATA,
      FslsplitOutputs,
      fslsplit,
      fslsplit_execute,
      fslsplit_params,
};
