// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const SPLIT_PARTS_GPU_METADATA: Metadata = {
    id: "a404b693a0e774169e36df28b7f0c6958f3fa3c3.boutiques",
    name: "split_parts_gpu",
    package: "fsl",
    container_image_tag: "brainlife/fsl:6.0.4-patched2",
};


interface SplitPartsGpuParameters {
    "@type"?: "fsl/split_parts_gpu";
    "datafile": InputPathType;
    "maskfile": InputPathType;
    "bvals_file": InputPathType;
    "bvecs_file": InputPathType;
    "grad_file"?: string | null | undefined;
    "use_grad_file": number;
    "total_num_parts": number;
    "output_directory": string;
}
type SplitPartsGpuParametersTagged = Required<Pick<SplitPartsGpuParameters, '@type'>> & SplitPartsGpuParameters;


/**
 * Output object returned when calling `SplitPartsGpuParameters(...)`.
 *
 * @interface
 */
interface SplitPartsGpuOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
}


/**
 * Build parameters.
 *
 * @param datafile Input data file
 * @param maskfile Input mask file
 * @param bvals_file bvals file
 * @param bvecs_file bvecs file
 * @param use_grad_file Use gradient file (0 or 1)
 * @param total_num_parts Total number of parts
 * @param output_directory Output directory
 * @param grad_file Gradient file (can be null)
 *
 * @returns Parameter dictionary
 */
function split_parts_gpu_params(
    datafile: InputPathType,
    maskfile: InputPathType,
    bvals_file: InputPathType,
    bvecs_file: InputPathType,
    use_grad_file: number,
    total_num_parts: number,
    output_directory: string,
    grad_file: string | null = null,
): SplitPartsGpuParametersTagged {
    const params = {
        "@type": "fsl/split_parts_gpu" as const,
        "datafile": datafile,
        "maskfile": maskfile,
        "bvals_file": bvals_file,
        "bvecs_file": bvecs_file,
        "use_grad_file": use_grad_file,
        "total_num_parts": total_num_parts,
        "output_directory": output_directory,
    };
    if (grad_file !== null) {
        params["grad_file"] = grad_file;
    }
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function split_parts_gpu_cargs(
    params: SplitPartsGpuParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("split_parts_gpu");
    cargs.push(execution.inputFile((params["datafile"] ?? null)));
    cargs.push(execution.inputFile((params["maskfile"] ?? null)));
    cargs.push(execution.inputFile((params["bvals_file"] ?? null)));
    cargs.push(execution.inputFile((params["bvecs_file"] ?? null)));
    if ((params["grad_file"] ?? null) !== null) {
        cargs.push((params["grad_file"] ?? null));
    }
    cargs.push(String((params["use_grad_file"] ?? null)));
    cargs.push(String((params["total_num_parts"] ?? null)));
    cargs.push((params["output_directory"] ?? null));
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function split_parts_gpu_outputs(
    params: SplitPartsGpuParameters,
    execution: Execution,
): SplitPartsGpuOutputs {
    const ret: SplitPartsGpuOutputs = {
        root: execution.outputFile("."),
    };
    return ret;
}


/**
 * split_parts_gpu
 *
 * Splits parts of data for GPU processing.
 *
 * Author: FMRIB Analysis Group, University of Oxford
 *
 * URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `SplitPartsGpuOutputs`).
 */
function split_parts_gpu_execute(
    params: SplitPartsGpuParameters,
    runner: Runner | null = null,
): SplitPartsGpuOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(SPLIT_PARTS_GPU_METADATA);
    params = execution.params(params)
    const cargs = split_parts_gpu_cargs(params, execution)
    const ret = split_parts_gpu_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * split_parts_gpu
 *
 * Splits parts of data for GPU processing.
 *
 * Author: FMRIB Analysis Group, University of Oxford
 *
 * URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
 *
 * @param datafile Input data file
 * @param maskfile Input mask file
 * @param bvals_file bvals file
 * @param bvecs_file bvecs file
 * @param use_grad_file Use gradient file (0 or 1)
 * @param total_num_parts Total number of parts
 * @param output_directory Output directory
 * @param grad_file Gradient file (can be null)
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `SplitPartsGpuOutputs`).
 */
function split_parts_gpu(
    datafile: InputPathType,
    maskfile: InputPathType,
    bvals_file: InputPathType,
    bvecs_file: InputPathType,
    use_grad_file: number,
    total_num_parts: number,
    output_directory: string,
    grad_file: string | null = null,
    runner: Runner | null = null,
): SplitPartsGpuOutputs {
    const params = split_parts_gpu_params(datafile, maskfile, bvals_file, bvecs_file, use_grad_file, total_num_parts, output_directory, grad_file)
    return split_parts_gpu_execute(params, runner);
}


export {
      SPLIT_PARTS_GPU_METADATA,
      SplitPartsGpuOutputs,
      split_parts_gpu,
      split_parts_gpu_execute,
      split_parts_gpu_params,
};
