// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const SURF_INFO_METADATA: Metadata = {
    id: "869be3f2fd4b338333ddb5e88a1f6d232910e89e.boutiques",
    name: "SurfInfo",
    package: "afni",
    container_image_tag: "afni/afni_make_build:AFNI_24.2.06",
};


interface SurfInfoParameters {
    "__STYXTYPE__": "SurfInfo";
    "surface": InputPathType;
    "com": boolean;
    "debug_level"?: number | null | undefined;
    "detail_level"?: number | null | undefined;
    "n_node": boolean;
    "n_faceset": boolean;
    "n_tri": boolean;
    "quiet": boolean;
    "separator"?: string | null | undefined;
    "input_surface"?: string | null | undefined;
    "surface_state"?: string | null | undefined;
    "surface_volume"?: InputPathType | null | undefined;
    "spec_file"?: InputPathType | null | undefined;
    "novolreg": boolean;
    "noxform": boolean;
    "setenv"?: string | null | undefined;
    "trace": boolean;
    "extreme_trace": boolean;
    "nomall": boolean;
    "yesmall": boolean;
}


function dynCargs(
    t: string,
): Function | undefined {
    /**
     * Get build cargs function by command type.
    
     * @param t Command type
    
     * @returns Build cargs function.
     */
    const cargsFuncs = {
        "SurfInfo": surf_info_cargs,
    };
    return cargsFuncs[t];
}


function dynOutputs(
    t: string,
): Function | undefined {
    /**
     * Get build outputs function by command type.
    
     * @param t Command type
    
     * @returns Build outputs function.
     */
    const outputsFuncs = {
        "SurfInfo": surf_info_outputs,
    };
    return outputsFuncs[t];
}


/**
 * Output object returned when calling `surf_info(...)`.
 *
 * @interface
 */
interface SurfInfoOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * Output file containing calculated surface metrics.
     */
    metrics_output: OutputPathType;
}


function surf_info_params(
    surface: InputPathType,
    com: boolean = false,
    debug_level: number | null = null,
    detail_level: number | null = null,
    n_node: boolean = false,
    n_faceset: boolean = false,
    n_tri: boolean = false,
    quiet: boolean = false,
    separator: string | null = null,
    input_surface: string | null = null,
    surface_state: string | null = null,
    surface_volume: InputPathType | null = null,
    spec_file: InputPathType | null = null,
    novolreg: boolean = false,
    noxform: boolean = false,
    setenv: string | null = null,
    trace: boolean = false,
    extreme_trace: boolean = false,
    nomall: boolean = false,
    yesmall: boolean = false,
): SurfInfoParameters {
    /**
     * Build parameters.
    
     * @param surface Input surface file.
     * @param com Output the center of mass.
     * @param debug_level Debugging level (2 turns LocalHead ON)
     * @param detail_level Calculate surface metrics. 1=yes, 0=no
     * @param n_node Output the number of nodes.
     * @param n_faceset Output the number of face sets.
     * @param n_tri Output the number of triangles.
     * @param quiet Do not include the name of the parameter in output.
     * @param separator Use string SEP to separate parameter values. Default is ' ; '
     * @param input_surface Specify the input surface type and file.
     * @param surface_state Specify surface type, state, and name.
     * @param surface_volume Specify a surface volume file.
     * @param spec_file Specify a surface specification (spec) file.
     * @param novolreg Ignore any Rotate, Volreg, Tagalign, or WarpDrive transformations present in the Surface Volume.
     * @param noxform Same as -novolreg.
     * @param setenv Set environment variable ENVname to be ENVvalue. Quotes are necessary.
     * @param trace Turns on In/Out debug and Memory tracing.
     * @param extreme_trace Turns on extreme tracing.
     * @param nomall Turn off memory tracing.
     * @param yesmall Turn on memory tracing (default).
    
     * @returns Parameter dictionary
     */
    const params = {
        "__STYXTYPE__": "SurfInfo" as const,
        "surface": surface,
        "com": com,
        "n_node": n_node,
        "n_faceset": n_faceset,
        "n_tri": n_tri,
        "quiet": quiet,
        "novolreg": novolreg,
        "noxform": noxform,
        "trace": trace,
        "extreme_trace": extreme_trace,
        "nomall": nomall,
        "yesmall": yesmall,
    };
    if (debug_level !== null) {
        params["debug_level"] = debug_level;
    }
    if (detail_level !== null) {
        params["detail_level"] = detail_level;
    }
    if (separator !== null) {
        params["separator"] = separator;
    }
    if (input_surface !== null) {
        params["input_surface"] = input_surface;
    }
    if (surface_state !== null) {
        params["surface_state"] = surface_state;
    }
    if (surface_volume !== null) {
        params["surface_volume"] = surface_volume;
    }
    if (spec_file !== null) {
        params["spec_file"] = spec_file;
    }
    if (setenv !== null) {
        params["setenv"] = setenv;
    }
    return params;
}


function surf_info_cargs(
    params: SurfInfoParameters,
    execution: Execution,
): string[] {
    /**
     * Build command-line arguments from parameters.
    
     * @param params The parameters.
     * @param execution The execution object for resolving input paths.
    
     * @returns Command-line arguments.
     */
    const cargs: string[] = [];
    cargs.push("SurfInfo");
    cargs.push(execution.inputFile((params["surface"] ?? null)));
    if ((params["com"] ?? null)) {
        cargs.push("-COM");
    }
    if ((params["debug_level"] ?? null) !== null) {
        cargs.push(
            "-debug",
            String((params["debug_level"] ?? null))
        );
    }
    if ((params["detail_level"] ?? null) !== null) {
        cargs.push(
            "-detail",
            String((params["detail_level"] ?? null))
        );
    }
    if ((params["n_node"] ?? null)) {
        cargs.push("-N_Node");
    }
    if ((params["n_faceset"] ?? null)) {
        cargs.push("-N_FaceSet");
    }
    if ((params["n_tri"] ?? null)) {
        cargs.push("-N_Tri");
    }
    if ((params["quiet"] ?? null)) {
        cargs.push("-quiet");
    }
    if ((params["separator"] ?? null) !== null) {
        cargs.push(
            "-sep",
            (params["separator"] ?? null)
        );
    }
    if ((params["input_surface"] ?? null) !== null) {
        cargs.push(
            "-i_TYPE",
            (params["input_surface"] ?? null)
        );
    }
    if ((params["surface_state"] ?? null) !== null) {
        cargs.push(
            "-tsn",
            (params["surface_state"] ?? null)
        );
    }
    if ((params["surface_volume"] ?? null) !== null) {
        cargs.push(
            "-sv",
            execution.inputFile((params["surface_volume"] ?? null))
        );
    }
    if ((params["spec_file"] ?? null) !== null) {
        cargs.push(
            "-spec",
            execution.inputFile((params["spec_file"] ?? null))
        );
    }
    if ((params["novolreg"] ?? null)) {
        cargs.push("-novolreg");
    }
    if ((params["noxform"] ?? null)) {
        cargs.push("-noxform");
    }
    if ((params["setenv"] ?? null) !== null) {
        cargs.push(
            "-setenv",
            (params["setenv"] ?? null)
        );
    }
    if ((params["trace"] ?? null)) {
        cargs.push("-trace");
    }
    if ((params["extreme_trace"] ?? null)) {
        cargs.push("-TRACE");
    }
    if ((params["nomall"] ?? null)) {
        cargs.push("-nomall");
    }
    if ((params["yesmall"] ?? null)) {
        cargs.push("-yesmall");
    }
    return cargs;
}


function surf_info_outputs(
    params: SurfInfoParameters,
    execution: Execution,
): SurfInfoOutputs {
    /**
     * Build outputs object containing output file paths and possibly stdout/stderr.
    
     * @param params The parameters.
     * @param execution The execution object for resolving input paths.
    
     * @returns Outputs object.
     */
    const ret: SurfInfoOutputs = {
        root: execution.outputFile("."),
        metrics_output: execution.outputFile([path.basename((params["surface"] ?? null)), "_metrics.txt"].join('')),
    };
    return ret;
}


function surf_info_execute(
    params: SurfInfoParameters,
    execution: Execution,
): SurfInfoOutputs {
    /**
     * Tool to gather information about surface files.
     * 
     * Author: AFNI Developers
     * 
     * URL: https://afni.nimh.nih.gov/
    
     * @param params The parameters.
     * @param execution The execution object.
    
     * @returns NamedTuple of outputs (described in `SurfInfoOutputs`).
     */
    params = execution.params(params)
    const cargs = surf_info_cargs(params, execution)
    const ret = surf_info_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


function surf_info(
    surface: InputPathType,
    com: boolean = false,
    debug_level: number | null = null,
    detail_level: number | null = null,
    n_node: boolean = false,
    n_faceset: boolean = false,
    n_tri: boolean = false,
    quiet: boolean = false,
    separator: string | null = null,
    input_surface: string | null = null,
    surface_state: string | null = null,
    surface_volume: InputPathType | null = null,
    spec_file: InputPathType | null = null,
    novolreg: boolean = false,
    noxform: boolean = false,
    setenv: string | null = null,
    trace: boolean = false,
    extreme_trace: boolean = false,
    nomall: boolean = false,
    yesmall: boolean = false,
    runner: Runner | null = null,
): SurfInfoOutputs {
    /**
     * Tool to gather information about surface files.
     * 
     * Author: AFNI Developers
     * 
     * URL: https://afni.nimh.nih.gov/
    
     * @param surface Input surface file.
     * @param com Output the center of mass.
     * @param debug_level Debugging level (2 turns LocalHead ON)
     * @param detail_level Calculate surface metrics. 1=yes, 0=no
     * @param n_node Output the number of nodes.
     * @param n_faceset Output the number of face sets.
     * @param n_tri Output the number of triangles.
     * @param quiet Do not include the name of the parameter in output.
     * @param separator Use string SEP to separate parameter values. Default is ' ; '
     * @param input_surface Specify the input surface type and file.
     * @param surface_state Specify surface type, state, and name.
     * @param surface_volume Specify a surface volume file.
     * @param spec_file Specify a surface specification (spec) file.
     * @param novolreg Ignore any Rotate, Volreg, Tagalign, or WarpDrive transformations present in the Surface Volume.
     * @param noxform Same as -novolreg.
     * @param setenv Set environment variable ENVname to be ENVvalue. Quotes are necessary.
     * @param trace Turns on In/Out debug and Memory tracing.
     * @param extreme_trace Turns on extreme tracing.
     * @param nomall Turn off memory tracing.
     * @param yesmall Turn on memory tracing (default).
     * @param runner Command runner
    
     * @returns NamedTuple of outputs (described in `SurfInfoOutputs`).
     */
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(SURF_INFO_METADATA);
    const params = surf_info_params(surface, com, debug_level, detail_level, n_node, n_faceset, n_tri, quiet, separator, input_surface, surface_state, surface_volume, spec_file, novolreg, noxform, setenv, trace, extreme_trace, nomall, yesmall)
    return surf_info_execute(params, execution);
}


export {
      SURF_INFO_METADATA,
      SurfInfoOutputs,
      SurfInfoParameters,
      surf_info,
      surf_info_params,
};
