// This file was auto generated by Styx.
// Do not edit this file directly.

import { Runner, Execution, Metadata, InputPathType, OutputPathType, getGlobalRunner } from 'styxdefs';

const V__SUMA_FSVOL_TO_BRIK_METADATA: Metadata = {
    id: "67ffbfb1c41a26dac3811235a2de927d197e7174.boutiques",
    name: "@SUMA_FSvolToBRIK",
    package: "afni",
    container_image_tag: "afni/afni_make_build:AFNI_24.2.06",
};


interface VSumaFsvolToBrikParameters {
    "@type"?: "afni/@SUMA_FSvolToBRIK";
    "fs_vol_data": InputPathType;
    "prefix": string;
}
type VSumaFsvolToBrikParametersTagged = Required<Pick<VSumaFsvolToBrikParameters, '@type'>> & VSumaFsvolToBrikParameters;


/**
 * Output object returned when calling `VSumaFsvolToBrikParameters(...)`.
 *
 * @interface
 */
interface VSumaFsvolToBrikOutputs {
    /**
     * Output root folder. This is the root folder for all outputs.
     */
    root: OutputPathType;
    /**
     * Output BRIK volume converted from FreeSurfer data
     */
    out_brik: OutputPathType;
    /**
     * Header file for the output BRIK volume
     */
    out_head: OutputPathType;
}


/**
 * Build parameters.
 *
 * @param fs_vol_data Input FreeSurfer volume data (e.g. COR- images or .mgz volume)
 * @param prefix Prefix for output BRIK volume
 *
 * @returns Parameter dictionary
 */
function v__suma_fsvol_to_brik_params(
    fs_vol_data: InputPathType,
    prefix: string,
): VSumaFsvolToBrikParametersTagged {
    const params = {
        "@type": "afni/@SUMA_FSvolToBRIK" as const,
        "fs_vol_data": fs_vol_data,
        "prefix": prefix,
    };
    return params;
}


/**
 * Build command-line arguments from parameters.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Command-line arguments.
 */
function v__suma_fsvol_to_brik_cargs(
    params: VSumaFsvolToBrikParameters,
    execution: Execution,
): string[] {
    const cargs: string[] = [];
    cargs.push("@SUMA_FSvolToBRIK");
    cargs.push(execution.inputFile((params["fs_vol_data"] ?? null)));
    cargs.push((params["prefix"] ?? null));
    return cargs;
}


/**
 * Build outputs object containing output file paths and possibly stdout/stderr.
 *
 * @param params The parameters.
 * @param execution The execution object for resolving input paths.
 *
 * @returns Outputs object.
 */
function v__suma_fsvol_to_brik_outputs(
    params: VSumaFsvolToBrikParameters,
    execution: Execution,
): VSumaFsvolToBrikOutputs {
    const ret: VSumaFsvolToBrikOutputs = {
        root: execution.outputFile("."),
        out_brik: execution.outputFile([(params["prefix"] ?? null), ".BRIK"].join('')),
        out_head: execution.outputFile([(params["prefix"] ?? null), ".HEAD"].join('')),
    };
    return ret;
}


/**
 * @SUMA_FSvolToBRIK
 *
 * A script to convert COR- or .mgz files from FreeSurfer to BRIK format.
 *
 * Author: AFNI Developers
 *
 * URL: https://afni.nimh.nih.gov/
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `VSumaFsvolToBrikOutputs`).
 */
function v__suma_fsvol_to_brik_execute(
    params: VSumaFsvolToBrikParameters,
    runner: Runner | null = null,
): VSumaFsvolToBrikOutputs {
    runner = runner || getGlobalRunner();
    const execution = runner.startExecution(V__SUMA_FSVOL_TO_BRIK_METADATA);
    params = execution.params(params)
    const cargs = v__suma_fsvol_to_brik_cargs(params, execution)
    const ret = v__suma_fsvol_to_brik_outputs(params, execution)
    execution.run(cargs, undefined);
    return ret;
}


/**
 * @SUMA_FSvolToBRIK
 *
 * A script to convert COR- or .mgz files from FreeSurfer to BRIK format.
 *
 * Author: AFNI Developers
 *
 * URL: https://afni.nimh.nih.gov/
 *
 * @param fs_vol_data Input FreeSurfer volume data (e.g. COR- images or .mgz volume)
 * @param prefix Prefix for output BRIK volume
 * @param runner Command runner
 *
 * @returns NamedTuple of outputs (described in `VSumaFsvolToBrikOutputs`).
 */
function v__suma_fsvol_to_brik(
    fs_vol_data: InputPathType,
    prefix: string,
    runner: Runner | null = null,
): VSumaFsvolToBrikOutputs {
    const params = v__suma_fsvol_to_brik_params(fs_vol_data, prefix)
    return v__suma_fsvol_to_brik_execute(params, runner);
}


export {
      VSumaFsvolToBrikOutputs,
      V__SUMA_FSVOL_TO_BRIK_METADATA,
      v__suma_fsvol_to_brik,
      v__suma_fsvol_to_brik_execute,
      v__suma_fsvol_to_brik_params,
};
