/**
 * MRTrix3
 *
 * MRtrix3 provides a set of tools to perform various types of diffusion MRI analyses, from various forms of tractography through to next-generation group-level analyses. It is designed with consistency, performance, and stability in mind, and is freely available under an open-source license. It is developed and maintained by a team of experts in the field, fostering an active community of users from diverse backgrounds.
 *
 * Author: MRTrix3 Developers
 *
 * URL: https://www.mrtrix.org/
 */
// This file was auto generated by Styx.
// Do not edit this file directly.

export {afdconnectivity, afdconnectivity_execute, afdconnectivity_params, afdconnectivity_config_params} from './mrtrix/afdconnectivity'
export {amp2response, amp2response_execute, amp2response_params, amp2response_config_params} from './mrtrix/amp2response'
export {amp2sh, amp2sh_execute, amp2sh_params, amp2sh_fslgrad_params, amp2sh_various_string_params, amp2sh_various_file_params, amp2sh_config_params} from './mrtrix/amp2sh'
export {connectome2tck, connectome2tck_execute, connectome2tck_params, connectome2tck_config_params} from './mrtrix/connectome2tck'
export {connectomeedit, connectomeedit_execute, connectomeedit_params, connectomeedit_config_params} from './mrtrix/connectomeedit'
export {connectomestats, connectomestats_execute, connectomestats_params, connectomestats_column_params, connectomestats_config_params} from './mrtrix/connectomestats'
export {dcmedit, dcmedit_execute, dcmedit_params, dcmedit_tag_params, dcmedit_config_params} from './mrtrix/dcmedit'
export {dcminfo, dcminfo_execute, dcminfo_params, dcminfo_tag_params, dcminfo_config_params} from './mrtrix/dcminfo'
export {dirflip, dirflip_execute, dirflip_params, dirflip_config_params} from './mrtrix/dirflip'
export {dirgen, dirgen_execute, dirgen_params, dirgen_config_params} from './mrtrix/dirgen'
export {dirmerge, dirmerge_execute, dirmerge_params, dirmerge_config_params} from './mrtrix/dirmerge'
export {dirorder, dirorder_execute, dirorder_params, dirorder_config_params} from './mrtrix/dirorder'
export {dirsplit, dirsplit_execute, dirsplit_params, dirsplit_config_params} from './mrtrix/dirsplit'
export {dirstat, dirstat_execute, dirstat_params, dirstat_fslgrad_params, dirstat_config_params} from './mrtrix/dirstat'
export {dwi2adc, dwi2adc_execute, dwi2adc_params, dwi2adc_fslgrad_params, dwi2adc_config_params} from './mrtrix/dwi2adc'
export {dwi2fod, dwi2fod_execute, dwi2fod_params, dwi2fod_fslgrad_params, dwi2fod_various_string_params, dwi2fod_various_file_params, dwi2fod_config_params, dwi2fod_response_odf_params} from './mrtrix/dwi2fod'
export {dwi2mask, dwi2mask_execute, dwi2mask_params, dwi2mask_fslgrad_params, dwi2mask_config_params} from './mrtrix/dwi2mask'
export {dwi2response, dwi2response_execute, dwi2response_params, dwi2response_dhollander_params, dwi2response_fa_params, dwi2response_manual_params, dwi2response_msmt_5tt_params, dwi2response_tax_params, dwi2response_tournier_params, dwi2response_fslgrad_params, dwi2response_config_params} from './mrtrix/dwi2response'
export {dwi2tensor, dwi2tensor_execute, dwi2tensor_params, dwi2tensor_fslgrad_params, dwi2tensor_config_params} from './mrtrix/dwi2tensor'
export {dwibiascorrect, dwibiascorrect_execute, dwibiascorrect_params, dwibiascorrect_fslgrad_params, dwibiascorrect_config_params} from './mrtrix/dwibiascorrect'
export {dwidenoise, dwidenoise_execute, dwidenoise_params, dwidenoise_config_params} from './mrtrix/dwidenoise'
export {dwiextract, dwiextract_execute, dwiextract_params, dwiextract_fslgrad_params, dwiextract_export_grad_fsl_params, dwiextract_import_pe_eddy_params, dwiextract_various_string_params, dwiextract_various_file_params, dwiextract_config_params} from './mrtrix/dwiextract'
export {dwigradcheck, dwigradcheck_execute, dwigradcheck_params, dwigradcheck_fslgrad_params, dwigradcheck_export_grad_fsl_params} from './mrtrix/dwigradcheck'
export {fixel2peaks, fixel2peaks_execute, fixel2peaks_params, fixel2peaks_config_params, fixel2peaks_various_string_params, fixel2peaks_various_file_params} from './mrtrix/fixel2peaks'
export {fixel2sh, fixel2sh_execute, fixel2sh_params, fixel2sh_config_params} from './mrtrix/fixel2sh'
export {fixel2tsf, fixel2tsf_execute, fixel2tsf_params, fixel2tsf_config_params} from './mrtrix/fixel2tsf'
export {fixel2voxel, fixel2voxel_execute, fixel2voxel_params, fixel2voxel_config_params} from './mrtrix/fixel2voxel'
export {fixelcfestats, fixelcfestats_execute, fixelcfestats_params, fixelcfestats_column_params, fixelcfestats_config_params, fixelcfestats_various_string_params, fixelcfestats_various_file_params} from './mrtrix/fixelcfestats'
export {fixelconnectivity, fixelconnectivity_execute, fixelconnectivity_params, fixelconnectivity_config_params} from './mrtrix/fixelconnectivity'
export {fixelconvert, fixelconvert_execute, fixelconvert_params, fixelconvert_config_params, fixelconvert_various_string_params, fixelconvert_various_file_params, fixelconvert_various_string_1_params, fixelconvert_various_file_1_params} from './mrtrix/fixelconvert'
export {fixelcorrespondence, fixelcorrespondence_execute, fixelcorrespondence_params, fixelcorrespondence_config_params} from './mrtrix/fixelcorrespondence'
export {fixelcrop, fixelcrop_execute, fixelcrop_params, fixelcrop_config_params} from './mrtrix/fixelcrop'
export {fixelfilter, fixelfilter_execute, fixelfilter_params, fixelfilter_config_params, fixelfilter_various_string_params, fixelfilter_various_file_params, fixelfilter_various_string_1_params, fixelfilter_various_file_1_params} from './mrtrix/fixelfilter'
export {fixelreorient, fixelreorient_execute, fixelreorient_params, fixelreorient_config_params} from './mrtrix/fixelreorient'
export {fod2dec, fod2dec_execute, fod2dec_params, fod2dec_config_params} from './mrtrix/fod2dec'
export {fod2fixel, fod2fixel_execute, fod2fixel_params, fod2fixel_config_params} from './mrtrix/fod2fixel'
export {label2colour, label2colour_execute, label2colour_params, label2colour_config_params} from './mrtrix/label2colour'
export {label2mesh, label2mesh_execute, label2mesh_params, label2mesh_config_params} from './mrtrix/label2mesh'
export {labelconvert, labelconvert_execute, labelconvert_params, labelconvert_config_params} from './mrtrix/labelconvert'
export {labelstats, labelstats_execute, labelstats_params, labelstats_config_params} from './mrtrix/labelstats'
export {maskdump, maskdump_execute, maskdump_params, maskdump_config_params} from './mrtrix/maskdump'
export {maskfilter, maskfilter_execute, maskfilter_params, maskfilter_various_string_params, maskfilter_various_file_params, maskfilter_config_params} from './mrtrix/maskfilter'
export {mesh2voxel, mesh2voxel_execute, mesh2voxel_params, mesh2voxel_config_params} from './mrtrix/mesh2voxel'
export {meshconvert, meshconvert_execute, meshconvert_params, meshconvert_transform_params, meshconvert_config_params} from './mrtrix/meshconvert'
export {meshfilter, meshfilter_execute, meshfilter_params, meshfilter_config_params} from './mrtrix/meshfilter'
export {mraverageheader, mraverageheader_execute, mraverageheader_params, mraverageheader_config_params} from './mrtrix/mraverageheader'
export {mrcalc, mrcalc_execute, mrcalc_params, mrcalc_abs_params, mrcalc_neg_params, mrcalc_add_params, mrcalc_subtract_params, mrcalc_multiply_params, mrcalc_divide_params, mrcalc_min_params, mrcalc_max_params, mrcalc_lt_params, mrcalc_gt_params, mrcalc_le_params, mrcalc_ge_params, mrcalc_eq_params, mrcalc_neq_params, mrcalc_if_params, mrcalc_replace_params, mrcalc_sqrt_params, mrcalc_pow_params, mrcalc_round_params, mrcalc_ceil_params, mrcalc_floor_params, mrcalc_not_params, mrcalc_and_params, mrcalc_or_params, mrcalc_xor_params, mrcalc_isnan_params, mrcalc_isinf_params, mrcalc_finite_params, mrcalc_complex_params, mrcalc_polar_params, mrcalc_real_params, mrcalc_imag_params, mrcalc_phase_params, mrcalc_conj_params, mrcalc_proj_params, mrcalc_exp_params, mrcalc_log_params, mrcalc_log10_params, mrcalc_cos_params, mrcalc_sin_params, mrcalc_tan_params, mrcalc_acos_params, mrcalc_asin_params, mrcalc_atan_params, mrcalc_cosh_params, mrcalc_sinh_params, mrcalc_tanh_params, mrcalc_acosh_params, mrcalc_asinh_params, mrcalc_atanh_params, mrcalc_config_params, mrcalc_various_string_params, mrcalc_various_file_params} from './mrtrix/mrcalc'
export {mrcat, mrcat_execute, mrcat_params, mrcat_config_params} from './mrtrix/mrcat'
export {mrcentroid, mrcentroid_execute, mrcentroid_params, mrcentroid_config_params} from './mrtrix/mrcentroid'
export {mrcheckerboardmask, mrcheckerboardmask_execute, mrcheckerboardmask_params, mrcheckerboardmask_config_params} from './mrtrix/mrcheckerboardmask'
export {mrclusterstats, mrclusterstats_execute, mrclusterstats_params, mrclusterstats_column_params, mrclusterstats_config_params} from './mrtrix/mrclusterstats'
export {mrcolour, mrcolour_execute, mrcolour_params, mrcolour_config_params} from './mrtrix/mrcolour'
export {mrconvert, mrconvert_execute, mrconvert_params, mrconvert_coord_params, mrconvert_clear_property_params, mrconvert_set_property_params, mrconvert_append_property_params, mrconvert_various_string_params, mrconvert_various_file_params, mrconvert_various_string_1_params, mrconvert_various_file_1_params, mrconvert_fslgrad_params, mrconvert_export_grad_fsl_params, mrconvert_import_pe_eddy_params, mrconvert_export_pe_eddy_params, mrconvert_config_params} from './mrtrix/mrconvert'
export {mrdegibbs, mrdegibbs_execute, mrdegibbs_params, mrdegibbs_config_params} from './mrtrix/mrdegibbs'
export {mrdump, mrdump_execute, mrdump_params, mrdump_config_params} from './mrtrix/mrdump'
export {mredit, mredit_execute, mredit_params, mredit_plane_params, mredit_sphere_params, mredit_voxel_params, mredit_config_params} from './mrtrix/mredit'
export {mrfilter, mrfilter_execute, mrfilter_params, mrfilter_various_string_params, mrfilter_various_file_params, mrfilter_config_params} from './mrtrix/mrfilter'
export {mrgrid, mrgrid_execute, mrgrid_params, mrgrid_axis_params, mrgrid_various_string_params, mrgrid_various_file_params, mrgrid_config_params} from './mrtrix/mrgrid'
export {mrhistmatch, mrhistmatch_execute, mrhistmatch_params, mrhistmatch_config_params} from './mrtrix/mrhistmatch'
export {mrhistogram, mrhistogram_execute, mrhistogram_params, mrhistogram_config_params} from './mrtrix/mrhistogram'
export {mrinfo, mrinfo_execute, mrinfo_params, mrinfo_property_params, mrinfo_fslgrad_params, mrinfo_export_grad_fsl_params, mrinfo_export_pe_eddy_params, mrinfo_config_params} from './mrtrix/mrinfo'
export {mrmath, mrmath_execute, mrmath_params, mrmath_config_params} from './mrtrix/mrmath'
export {mrmetric, mrmetric_execute, mrmetric_params, mrmetric_config_params} from './mrtrix/mrmetric'
export {mrregister, mrregister_execute, mrregister_params, mrregister_transformed_params, mrregister_transformed_midway_params, mrregister_nl_warp_params, mrregister_config_params} from './mrtrix/mrregister'
export {mrstats, mrstats_execute, mrstats_params, mrstats_output_params, mrstats_config_params} from './mrtrix/mrstats'
export {mrthreshold, mrthreshold_execute, mrthreshold_params, mrthreshold_config_params} from './mrtrix/mrthreshold'
export {mrtransform, mrtransform_execute, mrtransform_params, mrtransform_fslgrad_params, mrtransform_export_grad_fsl_params, mrtransform_various_string_params, mrtransform_various_file_params, mrtransform_config_params} from './mrtrix/mrtransform'
export {mtnormalise, mtnormalise_execute, mtnormalise_params, mtnormalise_config_params, mtnormalise_input_output_params} from './mrtrix/mtnormalise'
export {peaks2amp, peaks2amp_execute, peaks2amp_params, peaks2amp_config_params} from './mrtrix/peaks2amp'
export {peaks2fixel, peaks2fixel_execute, peaks2fixel_params, peaks2fixel_config_params} from './mrtrix/peaks2fixel'
export {responsemean, responsemean_execute, responsemean_params} from './mrtrix/responsemean'
export {sh2amp, sh2amp_execute, sh2amp_params, sh2amp_fslgrad_params, sh2amp_various_string_params, sh2amp_various_file_params, sh2amp_config_params} from './mrtrix/sh2amp'
export {sh2peaks, sh2peaks_execute, sh2peaks_params, sh2peaks_direction_params, sh2peaks_config_params} from './mrtrix/sh2peaks'
export {sh2power, sh2power_execute, sh2power_params, sh2power_config_params} from './mrtrix/sh2power'
export {sh2response, sh2response_execute, sh2response_params, sh2response_config_params} from './mrtrix/sh2response'
export {shbasis, shbasis_execute, shbasis_params, shbasis_config_params} from './mrtrix/shbasis'
export {shconv, shconv_execute, shconv_params, shconv_various_string_params, shconv_various_file_params, shconv_config_params} from './mrtrix/shconv'
export {tck2connectome, tck2connectome_execute, tck2connectome_params, tck2connectome_config_params} from './mrtrix/tck2connectome'
export {tck2fixel, tck2fixel_execute, tck2fixel_params, tck2fixel_config_params} from './mrtrix/tck2fixel'
export {tckconvert, tckconvert_execute, tckconvert_params, tckconvert_config_params, tckconvert_various_string_params, tckconvert_various_file_params} from './mrtrix/tckconvert'
export {tckdfc, tckdfc_execute, tckdfc_params, tckdfc_dynamic_params, tckdfc_config_params} from './mrtrix/tckdfc'
export {tckedit, tckedit_execute, tckedit_params, tckedit_include_params, tckedit_various_string_params, tckedit_various_file_params, tckedit_include_ordered_params, tckedit_exclude_params, tckedit_various_string_1_params, tckedit_various_file_1_params, tckedit_mask_params, tckedit_various_string_2_params, tckedit_various_file_2_params, tckedit_config_params} from './mrtrix/tckedit'
export {tckgen, tckgen_execute, tckgen_params, tckgen_seed_image_params, tckgen_seed_sphere_params, tckgen_seed_random_per_voxel_params, tckgen_seed_grid_per_voxel_params, tckgen_seed_rejection_params, tckgen_seed_gmwmi_params, tckgen_include_params, tckgen_various_string_params, tckgen_various_file_params, tckgen_include_ordered_params, tckgen_exclude_params, tckgen_various_string_1_params, tckgen_various_file_1_params, tckgen_mask_params, tckgen_various_string_2_params, tckgen_various_file_2_params, tckgen_fslgrad_params, tckgen_config_params} from './mrtrix/tckgen'
export {tckglobal, tckglobal_execute, tckglobal_params, tckglobal_riso_params, tckglobal_config_params} from './mrtrix/tckglobal'
export {tckinfo, tckinfo_execute, tckinfo_params, tckinfo_config_params} from './mrtrix/tckinfo'
export {tckmap, tckmap_execute, tckmap_params, tckmap_various_string_params, tckmap_various_file_params, tckmap_config_params} from './mrtrix/tckmap'
export {tckresample, tckresample_execute, tckresample_params, tckresample_line_params, tckresample_arc_params, tckresample_config_params} from './mrtrix/tckresample'
export {tcksample, tcksample_execute, tcksample_params, tcksample_config_params} from './mrtrix/tcksample'
export {tcksift, tcksift_execute, tcksift_params, tcksift_config_params} from './mrtrix/tcksift'
export {tcksift2, tcksift2_execute, tcksift2_params, tcksift2_config_params} from './mrtrix/tcksift2'
export {tckstats, tckstats_execute, tckstats_params, tckstats_output_params, tckstats_config_params} from './mrtrix/tckstats'
export {tcktransform, tcktransform_execute, tcktransform_params, tcktransform_config_params} from './mrtrix/tcktransform'
export {tensor2metric, tensor2metric_execute, tensor2metric_params, tensor2metric_config_params} from './mrtrix/tensor2metric'
export {transformcalc, transformcalc_execute, transformcalc_params, transformcalc_config_params} from './mrtrix/transformcalc'
export {transformcompose, transformcompose_execute, transformcompose_params, transformcompose_config_params, transformcompose_various_string_params, transformcompose_various_file_params} from './mrtrix/transformcompose'
export {transformconvert, transformconvert_execute, transformconvert_params, transformconvert_config_params} from './mrtrix/transformconvert'
export {tsfdivide, tsfdivide_execute, tsfdivide_params, tsfdivide_config_params} from './mrtrix/tsfdivide'
export {tsfinfo, tsfinfo_execute, tsfinfo_params, tsfinfo_config_params} from './mrtrix/tsfinfo'
export {tsfmult, tsfmult_execute, tsfmult_params, tsfmult_config_params} from './mrtrix/tsfmult'
export {tsfsmooth, tsfsmooth_execute, tsfsmooth_params, tsfsmooth_config_params} from './mrtrix/tsfsmooth'
export {tsfthreshold, tsfthreshold_execute, tsfthreshold_params, tsfthreshold_config_params} from './mrtrix/tsfthreshold'
export {tsfvalidate, tsfvalidate_execute, tsfvalidate_params, tsfvalidate_config_params} from './mrtrix/tsfvalidate'
export {v_5tt2gmwmi, v_5tt2gmwmi_execute, v_5tt2gmwmi_params, v_5tt2gmwmi_config_params} from './mrtrix/v_5tt2gmwmi'
export {v_5tt2vis, v_5tt2vis_execute, v_5tt2vis_params, v_5tt2vis_config_params} from './mrtrix/v_5tt2vis'
export {v_5ttcheck, v_5ttcheck_execute, v_5ttcheck_params, v_5ttcheck_config_params} from './mrtrix/v_5ttcheck'
export {v_5ttedit, v_5ttedit_execute, v_5ttedit_params, v_5ttedit_config_params} from './mrtrix/v_5ttedit'
export {v_5ttgen, v_5ttgen_execute, v_5ttgen_params, v_5ttgen_freesurfer_params, v_5ttgen_fsl_params, v_5ttgen_gif_params, v_5ttgen_hsvs_params, v_5ttgen_config_params} from './mrtrix/v_5ttgen'
export {vectorstats, vectorstats_execute, vectorstats_params, vectorstats_column_params, vectorstats_config_params} from './mrtrix/vectorstats'
export {voxel2fixel, voxel2fixel_execute, voxel2fixel_params, voxel2fixel_config_params} from './mrtrix/voxel2fixel'
export {voxel2mesh, voxel2mesh_execute, voxel2mesh_params, voxel2mesh_config_params} from './mrtrix/voxel2mesh'
export {warp2metric, warp2metric_execute, warp2metric_params, warp2metric_fc_params, warp2metric_config_params} from './mrtrix/warp2metric'
export {warpconvert, warpconvert_execute, warpconvert_params, warpconvert_config_params} from './mrtrix/warpconvert'
export {warpcorrect, warpcorrect_execute, warpcorrect_params, warpcorrect_config_params} from './mrtrix/warpcorrect'
export {warpinit, warpinit_execute, warpinit_params, warpinit_config_params} from './mrtrix/warpinit'
export {warpinvert, warpinvert_execute, warpinvert_params, warpinvert_config_params} from './mrtrix/warpinvert'
import { Runner } from 'styxdefs';
import { afdconnectivity_execute } from './mrtrix/afdconnectivity'
import { amp2response_execute } from './mrtrix/amp2response'
import { amp2sh_execute } from './mrtrix/amp2sh'
import { connectome2tck_execute } from './mrtrix/connectome2tck'
import { connectomeedit_execute } from './mrtrix/connectomeedit'
import { connectomestats_execute } from './mrtrix/connectomestats'
import { dcmedit_execute } from './mrtrix/dcmedit'
import { dcminfo_execute } from './mrtrix/dcminfo'
import { dirflip_execute } from './mrtrix/dirflip'
import { dirgen_execute } from './mrtrix/dirgen'
import { dirmerge_execute } from './mrtrix/dirmerge'
import { dirorder_execute } from './mrtrix/dirorder'
import { dirsplit_execute } from './mrtrix/dirsplit'
import { dirstat_execute } from './mrtrix/dirstat'
import { dwi2adc_execute } from './mrtrix/dwi2adc'
import { dwi2fod_execute } from './mrtrix/dwi2fod'
import { dwi2mask_execute } from './mrtrix/dwi2mask'
import { dwi2response_execute } from './mrtrix/dwi2response'
import { dwi2tensor_execute } from './mrtrix/dwi2tensor'
import { dwibiascorrect_execute } from './mrtrix/dwibiascorrect'
import { dwidenoise_execute } from './mrtrix/dwidenoise'
import { dwiextract_execute } from './mrtrix/dwiextract'
import { dwigradcheck_execute } from './mrtrix/dwigradcheck'
import { fixel2peaks_execute } from './mrtrix/fixel2peaks'
import { fixel2sh_execute } from './mrtrix/fixel2sh'
import { fixel2tsf_execute } from './mrtrix/fixel2tsf'
import { fixel2voxel_execute } from './mrtrix/fixel2voxel'
import { fixelcfestats_execute } from './mrtrix/fixelcfestats'
import { fixelconnectivity_execute } from './mrtrix/fixelconnectivity'
import { fixelconvert_execute } from './mrtrix/fixelconvert'
import { fixelcorrespondence_execute } from './mrtrix/fixelcorrespondence'
import { fixelcrop_execute } from './mrtrix/fixelcrop'
import { fixelfilter_execute } from './mrtrix/fixelfilter'
import { fixelreorient_execute } from './mrtrix/fixelreorient'
import { fod2dec_execute } from './mrtrix/fod2dec'
import { fod2fixel_execute } from './mrtrix/fod2fixel'
import { label2colour_execute } from './mrtrix/label2colour'
import { label2mesh_execute } from './mrtrix/label2mesh'
import { labelconvert_execute } from './mrtrix/labelconvert'
import { labelstats_execute } from './mrtrix/labelstats'
import { maskdump_execute } from './mrtrix/maskdump'
import { maskfilter_execute } from './mrtrix/maskfilter'
import { mesh2voxel_execute } from './mrtrix/mesh2voxel'
import { meshconvert_execute } from './mrtrix/meshconvert'
import { meshfilter_execute } from './mrtrix/meshfilter'
import { mraverageheader_execute } from './mrtrix/mraverageheader'
import { mrcalc_execute } from './mrtrix/mrcalc'
import { mrcat_execute } from './mrtrix/mrcat'
import { mrcentroid_execute } from './mrtrix/mrcentroid'
import { mrcheckerboardmask_execute } from './mrtrix/mrcheckerboardmask'
import { mrclusterstats_execute } from './mrtrix/mrclusterstats'
import { mrcolour_execute } from './mrtrix/mrcolour'
import { mrconvert_execute } from './mrtrix/mrconvert'
import { mrdegibbs_execute } from './mrtrix/mrdegibbs'
import { mrdump_execute } from './mrtrix/mrdump'
import { mredit_execute } from './mrtrix/mredit'
import { mrfilter_execute } from './mrtrix/mrfilter'
import { mrgrid_execute } from './mrtrix/mrgrid'
import { mrhistmatch_execute } from './mrtrix/mrhistmatch'
import { mrhistogram_execute } from './mrtrix/mrhistogram'
import { mrinfo_execute } from './mrtrix/mrinfo'
import { mrmath_execute } from './mrtrix/mrmath'
import { mrmetric_execute } from './mrtrix/mrmetric'
import { mrregister_execute } from './mrtrix/mrregister'
import { mrstats_execute } from './mrtrix/mrstats'
import { mrthreshold_execute } from './mrtrix/mrthreshold'
import { mrtransform_execute } from './mrtrix/mrtransform'
import { mtnormalise_execute } from './mrtrix/mtnormalise'
import { peaks2amp_execute } from './mrtrix/peaks2amp'
import { peaks2fixel_execute } from './mrtrix/peaks2fixel'
import { responsemean_execute } from './mrtrix/responsemean'
import { sh2amp_execute } from './mrtrix/sh2amp'
import { sh2peaks_execute } from './mrtrix/sh2peaks'
import { sh2power_execute } from './mrtrix/sh2power'
import { sh2response_execute } from './mrtrix/sh2response'
import { shbasis_execute } from './mrtrix/shbasis'
import { shconv_execute } from './mrtrix/shconv'
import { tck2connectome_execute } from './mrtrix/tck2connectome'
import { tck2fixel_execute } from './mrtrix/tck2fixel'
import { tckconvert_execute } from './mrtrix/tckconvert'
import { tckdfc_execute } from './mrtrix/tckdfc'
import { tckedit_execute } from './mrtrix/tckedit'
import { tckgen_execute } from './mrtrix/tckgen'
import { tckglobal_execute } from './mrtrix/tckglobal'
import { tckinfo_execute } from './mrtrix/tckinfo'
import { tckmap_execute } from './mrtrix/tckmap'
import { tckresample_execute } from './mrtrix/tckresample'
import { tcksample_execute } from './mrtrix/tcksample'
import { tcksift2_execute } from './mrtrix/tcksift2'
import { tcksift_execute } from './mrtrix/tcksift'
import { tckstats_execute } from './mrtrix/tckstats'
import { tcktransform_execute } from './mrtrix/tcktransform'
import { tensor2metric_execute } from './mrtrix/tensor2metric'
import { transformcalc_execute } from './mrtrix/transformcalc'
import { transformcompose_execute } from './mrtrix/transformcompose'
import { transformconvert_execute } from './mrtrix/transformconvert'
import { tsfdivide_execute } from './mrtrix/tsfdivide'
import { tsfinfo_execute } from './mrtrix/tsfinfo'
import { tsfmult_execute } from './mrtrix/tsfmult'
import { tsfsmooth_execute } from './mrtrix/tsfsmooth'
import { tsfthreshold_execute } from './mrtrix/tsfthreshold'
import { tsfvalidate_execute } from './mrtrix/tsfvalidate'
import { v_5tt2gmwmi_execute } from './mrtrix/v_5tt2gmwmi'
import { v_5tt2vis_execute } from './mrtrix/v_5tt2vis'
import { v_5ttcheck_execute } from './mrtrix/v_5ttcheck'
import { v_5ttedit_execute } from './mrtrix/v_5ttedit'
import { v_5ttgen_execute } from './mrtrix/v_5ttgen'
import { vectorstats_execute } from './mrtrix/vectorstats'
import { voxel2fixel_execute } from './mrtrix/voxel2fixel'
import { voxel2mesh_execute } from './mrtrix/voxel2mesh'
import { warp2metric_execute } from './mrtrix/warp2metric'
import { warpconvert_execute } from './mrtrix/warpconvert'
import { warpcorrect_execute } from './mrtrix/warpcorrect'
import { warpinit_execute } from './mrtrix/warpinit'
import { warpinvert_execute } from './mrtrix/warpinvert'


/**
 * Run a command in this package dynamically from a params object.
 *
 * @param params The parameters.
 * @param runner Command runner
 *
 */
function execute(
    params: any,
    runner: Runner | null = null,
) {
    return {
        "mrtrix/5tt2gmwmi": v_5tt2gmwmi_execute,
        "mrtrix/5tt2vis": v_5tt2vis_execute,
        "mrtrix/5ttcheck": v_5ttcheck_execute,
        "mrtrix/5ttedit": v_5ttedit_execute,
        "mrtrix/5ttgen": v_5ttgen_execute,
        "mrtrix/afdconnectivity": afdconnectivity_execute,
        "mrtrix/amp2response": amp2response_execute,
        "mrtrix/amp2sh": amp2sh_execute,
        "mrtrix/connectome2tck": connectome2tck_execute,
        "mrtrix/connectomeedit": connectomeedit_execute,
        "mrtrix/connectomestats": connectomestats_execute,
        "mrtrix/dcmedit": dcmedit_execute,
        "mrtrix/dcminfo": dcminfo_execute,
        "mrtrix/dirflip": dirflip_execute,
        "mrtrix/dirgen": dirgen_execute,
        "mrtrix/dirmerge": dirmerge_execute,
        "mrtrix/dirorder": dirorder_execute,
        "mrtrix/dirsplit": dirsplit_execute,
        "mrtrix/dirstat": dirstat_execute,
        "mrtrix/dwi2adc": dwi2adc_execute,
        "mrtrix/dwi2fod": dwi2fod_execute,
        "mrtrix/dwi2mask": dwi2mask_execute,
        "mrtrix/dwi2response": dwi2response_execute,
        "mrtrix/dwi2tensor": dwi2tensor_execute,
        "mrtrix/dwibiascorrect": dwibiascorrect_execute,
        "mrtrix/dwidenoise": dwidenoise_execute,
        "mrtrix/dwiextract": dwiextract_execute,
        "mrtrix/dwigradcheck": dwigradcheck_execute,
        "mrtrix/fixel2peaks": fixel2peaks_execute,
        "mrtrix/fixel2sh": fixel2sh_execute,
        "mrtrix/fixel2tsf": fixel2tsf_execute,
        "mrtrix/fixel2voxel": fixel2voxel_execute,
        "mrtrix/fixelcfestats": fixelcfestats_execute,
        "mrtrix/fixelconnectivity": fixelconnectivity_execute,
        "mrtrix/fixelconvert": fixelconvert_execute,
        "mrtrix/fixelcorrespondence": fixelcorrespondence_execute,
        "mrtrix/fixelcrop": fixelcrop_execute,
        "mrtrix/fixelfilter": fixelfilter_execute,
        "mrtrix/fixelreorient": fixelreorient_execute,
        "mrtrix/fod2dec": fod2dec_execute,
        "mrtrix/fod2fixel": fod2fixel_execute,
        "mrtrix/label2colour": label2colour_execute,
        "mrtrix/label2mesh": label2mesh_execute,
        "mrtrix/labelconvert": labelconvert_execute,
        "mrtrix/labelstats": labelstats_execute,
        "mrtrix/maskdump": maskdump_execute,
        "mrtrix/maskfilter": maskfilter_execute,
        "mrtrix/mesh2voxel": mesh2voxel_execute,
        "mrtrix/meshconvert": meshconvert_execute,
        "mrtrix/meshfilter": meshfilter_execute,
        "mrtrix/mraverageheader": mraverageheader_execute,
        "mrtrix/mrcalc": mrcalc_execute,
        "mrtrix/mrcat": mrcat_execute,
        "mrtrix/mrcentroid": mrcentroid_execute,
        "mrtrix/mrcheckerboardmask": mrcheckerboardmask_execute,
        "mrtrix/mrclusterstats": mrclusterstats_execute,
        "mrtrix/mrcolour": mrcolour_execute,
        "mrtrix/mrconvert": mrconvert_execute,
        "mrtrix/mrdegibbs": mrdegibbs_execute,
        "mrtrix/mrdump": mrdump_execute,
        "mrtrix/mredit": mredit_execute,
        "mrtrix/mrfilter": mrfilter_execute,
        "mrtrix/mrgrid": mrgrid_execute,
        "mrtrix/mrhistmatch": mrhistmatch_execute,
        "mrtrix/mrhistogram": mrhistogram_execute,
        "mrtrix/mrinfo": mrinfo_execute,
        "mrtrix/mrmath": mrmath_execute,
        "mrtrix/mrmetric": mrmetric_execute,
        "mrtrix/mrregister": mrregister_execute,
        "mrtrix/mrstats": mrstats_execute,
        "mrtrix/mrthreshold": mrthreshold_execute,
        "mrtrix/mrtransform": mrtransform_execute,
        "mrtrix/mtnormalise": mtnormalise_execute,
        "mrtrix/peaks2amp": peaks2amp_execute,
        "mrtrix/peaks2fixel": peaks2fixel_execute,
        "mrtrix/responsemean": responsemean_execute,
        "mrtrix/sh2amp": sh2amp_execute,
        "mrtrix/sh2peaks": sh2peaks_execute,
        "mrtrix/sh2power": sh2power_execute,
        "mrtrix/sh2response": sh2response_execute,
        "mrtrix/shbasis": shbasis_execute,
        "mrtrix/shconv": shconv_execute,
        "mrtrix/tck2connectome": tck2connectome_execute,
        "mrtrix/tck2fixel": tck2fixel_execute,
        "mrtrix/tckconvert": tckconvert_execute,
        "mrtrix/tckdfc": tckdfc_execute,
        "mrtrix/tckedit": tckedit_execute,
        "mrtrix/tckgen": tckgen_execute,
        "mrtrix/tckglobal": tckglobal_execute,
        "mrtrix/tckinfo": tckinfo_execute,
        "mrtrix/tckmap": tckmap_execute,
        "mrtrix/tckresample": tckresample_execute,
        "mrtrix/tcksample": tcksample_execute,
        "mrtrix/tcksift": tcksift_execute,
        "mrtrix/tcksift2": tcksift2_execute,
        "mrtrix/tckstats": tckstats_execute,
        "mrtrix/tcktransform": tcktransform_execute,
        "mrtrix/tensor2metric": tensor2metric_execute,
        "mrtrix/transformcalc": transformcalc_execute,
        "mrtrix/transformcompose": transformcompose_execute,
        "mrtrix/transformconvert": transformconvert_execute,
        "mrtrix/tsfdivide": tsfdivide_execute,
        "mrtrix/tsfinfo": tsfinfo_execute,
        "mrtrix/tsfmult": tsfmult_execute,
        "mrtrix/tsfsmooth": tsfsmooth_execute,
        "mrtrix/tsfthreshold": tsfthreshold_execute,
        "mrtrix/tsfvalidate": tsfvalidate_execute,
        "mrtrix/vectorstats": vectorstats_execute,
        "mrtrix/voxel2fixel": voxel2fixel_execute,
        "mrtrix/voxel2mesh": voxel2mesh_execute,
        "mrtrix/warp2metric": warp2metric_execute,
        "mrtrix/warpconvert": warpconvert_execute,
        "mrtrix/warpcorrect": warpcorrect_execute,
        "mrtrix/warpinit": warpinit_execute,
        "mrtrix/warpinvert": warpinvert_execute,
    }[params["@type"]](params, runner)
}


export {
      execute,
};
